FROM python:3.12-slim

WORKDIR /app

RUN pip install --trusted-host pypi.org --trusted-host files.pythonhosted.org poetry

COPY pyproject.toml poetry.lock* ./

RUN poetry config virtualenvs.create false \
    && poetry config certificates.default.cert false \
    && poetry install --no-interaction --no-ansi

COPY backend/ ./

CMD ["poetry", "run", "uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
