"use client";

import { useState, useEffect } from "react";
import { api, DashboardStats, Activity } from "@/lib/api";

export default function Dashboard() {
  const [stats, setStats] = useState<DashboardStats | null>(null);
  const [activity, setActivity] = useState<Activity[]>([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);

  useEffect(() => {
    fetchData();
    const interval = setInterval(fetchData, 30000);
    return () => clearInterval(interval);
  }, []);

  const fetchData = async () => {
    try {
      setLoading(true);
      setError(null);
      const [statsData, activityData] = await Promise.all([
        api.getDashboardStats(),
        api.getRecentActivity(10),
      ]);
      setStats(statsData);
      setActivity(activityData);
    } catch (err) {
      console.error("Error fetching dashboard data:", err);
      setError("Failed to load dashboard data");
    } finally {
      setLoading(false);
    }
  };

  const getActivityIcon = (type: string) => {
    switch (type) {
      case "template_created":
        return "📝";
      case "report_generated":
        return "📊";
      default:
        return "📌";
    }
  };

  const getActivityText = (item: Activity) => {
    switch (item.type) {
      case "template_created":
        return `Template "${item.data.name}" was created`;
      case "report_generated":
        return `Report "${item.data.title}" was generated by ${item.data.generated_by}`;
      default:
        return "Activity occurred";
    }
  };

  return (
    <div className="min-h-screen bg-gray-50">
      <nav className="bg-white shadow-sm border-b border-gray-100">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="flex justify-between h-16">
            <div className="flex items-center">
              <h1 className="text-xl font-semibold text-gray-900">Ledgerly</h1>
            </div>
            <div className="flex items-center gap-4">
              <a
                href="/audits"
                className="text-gray-700 hover:text-gray-900 px-3 py-2 rounded-md text-sm font-medium"
              >
                Audits
              </a>
              <a
                href="/reports"
                className="text-gray-700 hover:text-gray-900 px-3 py-2 rounded-md text-sm font-medium"
              >
                Reports
              </a>
              <button className="text-gray-700 hover:text-gray-900 px-3 py-2 rounded-md text-sm font-medium">
                Logout
              </button>
            </div>
          </div>
        </div>
      </nav>

      <main className="max-w-7xl mx-auto py-6 sm:px-6 lg:px-8">
        <div className="px-4 py-6 sm:px-0">
          <div className="flex justify-between items-center mb-6">
            <h2 className="text-2xl font-semibold text-gray-900">Dashboard</h2>
            <button
              onClick={fetchData}
              className="px-4 py-2 text-sm text-gray-700 bg-white border border-gray-300 rounded-lg hover:bg-gray-50"
            >
              Refresh
            </button>
          </div>

          {error && (
            <div className="mb-6 bg-red-50 border border-red-200 text-red-700 px-4 py-3 rounded-lg">
              {error}
            </div>
          )}

          {loading && !stats ? (
            <div className="text-center py-12">
              <p className="text-gray-500">Loading dashboard...</p>
            </div>
          ) : stats ? (
            <>
              <div className="grid grid-cols-1 gap-6 sm:grid-cols-2 lg:grid-cols-4 mb-8">
                <div className="bg-white overflow-hidden rounded-2xl shadow-sm border border-gray-100 p-6">
                  <h3 className="text-sm font-medium text-gray-500">Total Templates</h3>
                  <p className="mt-2 text-3xl font-semibold text-blue-600">{stats.overview.total_templates}</p>
                  <p className="mt-1 text-xs text-gray-400">
                    +{stats.overview.recent_templates_30d} in last 30 days
                  </p>
                </div>
                <div className="bg-white overflow-hidden rounded-2xl shadow-sm border border-gray-100 p-6">
                  <h3 className="text-sm font-medium text-gray-500">Total Reports</h3>
                  <p className="mt-2 text-3xl font-semibold text-green-600">{stats.overview.total_reports}</p>
                  <p className="mt-1 text-xs text-gray-400">
                    +{stats.overview.recent_reports_30d} in last 30 days
                  </p>
                </div>
                <div className="bg-white overflow-hidden rounded-2xl shadow-sm border border-gray-100 p-6">
                  <h3 className="text-sm font-medium text-gray-500">Comments</h3>
                  <p className="mt-2 text-3xl font-semibold text-purple-600">{stats.overview.total_comments}</p>
                  <p className="mt-1 text-xs text-gray-400">Total discussions</p>
                </div>
                <div className="bg-white overflow-hidden rounded-2xl shadow-sm border border-gray-100 p-6">
                  <h3 className="text-sm font-medium text-gray-500">Storage Used</h3>
                  <p className="mt-2 text-3xl font-semibold text-orange-600">
                    {stats.overview.total_storage_mb} MB
                  </p>
                  <p className="mt-1 text-xs text-gray-400">
                    {stats.overview.total_attachments} files
                  </p>
                </div>
              </div>

              <div className="grid grid-cols-1 lg:grid-cols-3 gap-6 mb-8">
                <div className="bg-white rounded-2xl shadow-sm border border-gray-100 p-6">
                  <h3 className="text-lg font-semibold text-gray-900 mb-4">Templates by Status</h3>
                  <div className="space-y-3">
                    <div>
                      <div className="flex justify-between items-center mb-1">
                        <span className="text-sm text-gray-600">Draft</span>
                        <span className="text-sm font-medium text-gray-900">{stats.templates_by_status.draft}</span>
                      </div>
                      <div className="w-full bg-gray-200 rounded-full h-2">
                        <div
                          className="bg-gray-600 h-2 rounded-full"
                          style={{
                            width: `${(stats.templates_by_status.draft / stats.overview.total_templates) * 100}%`
                          }}
                        ></div>
                      </div>
                    </div>
                    <div>
                      <div className="flex justify-between items-center mb-1">
                        <span className="text-sm text-gray-600">Active</span>
                        <span className="text-sm font-medium text-gray-900">{stats.templates_by_status.active}</span>
                      </div>
                      <div className="w-full bg-gray-200 rounded-full h-2">
                        <div
                          className="bg-green-600 h-2 rounded-full"
                          style={{
                            width: `${(stats.templates_by_status.active / stats.overview.total_templates) * 100}%`
                          }}
                        ></div>
                      </div>
                    </div>
                    <div>
                      <div className="flex justify-between items-center mb-1">
                        <span className="text-sm text-gray-600">Archived</span>
                        <span className="text-sm font-medium text-gray-900">{stats.templates_by_status.archived}</span>
                      </div>
                      <div className="w-full bg-gray-200 rounded-full h-2">
                        <div
                          className="bg-red-600 h-2 rounded-full"
                          style={{
                            width: `${(stats.templates_by_status.archived / stats.overview.total_templates) * 100}%`
                          }}
                        ></div>
                      </div>
                    </div>
                  </div>
                </div>

                <div className="bg-white rounded-2xl shadow-sm border border-gray-100 p-6">
                  <h3 className="text-lg font-semibold text-gray-900 mb-4">Most Commented</h3>
                  {stats.top_templates.most_commented.length === 0 ? (
                    <p className="text-sm text-gray-500">No comments yet</p>
                  ) : (
                    <div className="space-y-2">
                      {stats.top_templates.most_commented.map((template) => (
                        <div key={template.id} className="flex justify-between items-center py-2 border-b border-gray-100 last:border-0">
                          <span className="text-sm text-gray-900 truncate flex-1">{template.name}</span>
                          <span className="ml-2 text-sm font-medium text-blue-600">{template.comments}</span>
                        </div>
                      ))}
                    </div>
                  )}
                </div>

                <div className="bg-white rounded-2xl shadow-sm border border-gray-100 p-6">
                  <h3 className="text-lg font-semibold text-gray-900 mb-4">Most Attachments</h3>
                  {stats.top_templates.most_attachments.length === 0 ? (
                    <p className="text-sm text-gray-500">No attachments yet</p>
                  ) : (
                    <div className="space-y-2">
                      {stats.top_templates.most_attachments.map((template) => (
                        <div key={template.id} className="flex justify-between items-center py-2 border-b border-gray-100 last:border-0">
                          <span className="text-sm text-gray-900 truncate flex-1">{template.name}</span>
                          <span className="ml-2 text-sm font-medium text-green-600">{template.attachments}</span>
                        </div>
                      ))}
                    </div>
                  )}
                </div>
              </div>

              <div className="grid grid-cols-1 lg:grid-cols-2 gap-6 mb-8">
                <div className="bg-white rounded-2xl shadow-sm border border-gray-100 p-6">
                  <h3 className="text-lg font-semibold text-gray-900 mb-4">Templates Created (Last 12 Months)</h3>
                  {stats.trends.templates_per_month.length === 0 ? (
                    <p className="text-sm text-gray-500 text-center py-8">No data available</p>
                  ) : (
                    <div className="space-y-2">
                      {stats.trends.templates_per_month.slice(-6).map((item) => (
                        <div key={item.label}>
                          <div className="flex justify-between items-center mb-1">
                            <span className="text-xs text-gray-600">{item.label}</span>
                            <span className="text-xs font-medium text-gray-900">{item.count}</span>
                          </div>
                          <div className="w-full bg-gray-200 rounded-full h-2">
                            <div
                              className="bg-blue-600 h-2 rounded-full"
                              style={{
                                width: `${Math.min((item.count / Math.max(...stats.trends.templates_per_month.map(i => i.count))) * 100, 100)}%`
                              }}
                            ></div>
                          </div>
                        </div>
                      ))}
                    </div>
                  )}
                </div>

                <div className="bg-white rounded-2xl shadow-sm border border-gray-100 p-6">
                  <h3 className="text-lg font-semibold text-gray-900 mb-4">Recent Activity</h3>
                  {activity.length === 0 ? (
                    <p className="text-sm text-gray-500 text-center py-8">No recent activity</p>
                  ) : (
                    <div className="space-y-3">
                      {activity.map((item, index) => (
                        <div key={index} className="flex gap-3 pb-3 border-b border-gray-100 last:border-0">
                          <span className="text-2xl">{getActivityIcon(item.type)}</span>
                          <div className="flex-1 min-w-0">
                            <p className="text-sm text-gray-900">{getActivityText(item)}</p>
                            <p className="text-xs text-gray-500 mt-1">
                              {new Date(item.timestamp).toLocaleString()}
                            </p>
                          </div>
                        </div>
                      ))}
                    </div>
                  )}
                </div>
              </div>

              <div className="grid grid-cols-1 gap-6 sm:grid-cols-2">
                <a href="/audits" className="block">
                  <div className="bg-blue-50 border-2 border-blue-200 rounded-2xl p-6 hover:bg-blue-100 transition-colors">
                    <h3 className="text-lg font-semibold text-blue-900">Create Template</h3>
                    <p className="mt-2 text-sm text-blue-700">Start building a new audit template</p>
                  </div>
                </a>
                <a href="/reports" className="block">
                  <div className="bg-green-50 border-2 border-green-200 rounded-2xl p-6 hover:bg-green-100 transition-colors">
                    <h3 className="text-lg font-semibold text-green-900">Generate Report</h3>
                    <p className="mt-2 text-sm text-green-700">Create a new audit report from a template</p>
                  </div>
                </a>
              </div>
            </>
          ) : null}
        </div>
      </main>
    </div>
  );
}
